# metricbeat
- name: Copy metricbeat.yml config file to the hosts
  become: yes
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  register: metricbeatcfg
  tags:
    - config

- name: Copy RedELK CA file to the hosts
  become: yes
  copy:
    src: certificates/redelk/redelkCA.crt
    dest: /etc/metricbeat/redelkCA.crt
  register: redelkca
  tags:
    - pki

- name: Recursively setting permissions of /etc/metricbeat folder
  become: yes
  file:
    path: /etc/metricbeat
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: u=rwX,g=rX,o=-rwx
  tags:
    - config

- name: Restarting metricbeat and enabling on boot
  become: yes
  service:
    name: metricbeat
    state: restarted
    enabled: yes
  when: metricbeatcfg.changed or redelkca.changed
  tags:
    - services
